### ISSUE TITLE
Can it support paging3 data？

### ISSUE THREAD

**Issue by choristery** [oleksandrbalan/pagecurl#8]

**Comment by oleksandrbalan** [comment]
Hi 👋 

I am afraid it is not possible right now.

The `PageCurlState` has `max` defined as a property, thus when Paging3 loads a new page with data the new `PageCurlState` must be created with different `max` value. I have created a small PoC, where `max` is defined as lambda, which returns Int as `max` value and it kinda works. But I have to test it properly and then I could implement it in some release.

**Comment by choristery** [comment]
Thank you.

Perhaps refer to LazyListState? By remembering the position through keys, the existing UI state can still be maintained when the data is updated. Supporting paging will make the component more practical. In practical applications, there are far more dynamic paging data scenarios than fixed data scenarios.

**Comment by oleksandrbalan** [comment]
> Perhaps refer to LazyListState

I would say `PageCurl` is more like a `Pager` from foundation than `LazyLayout`. That's also why I changed API a little bit and now count of pages is now defined via `count` argument in `PageCurl` composable instead of `max` argument in `rememberPageCurlState` method.

See changes in #10

> Supporting paging

With that change it is now possible 🥳 

See demo example:
https://github.com/oleksandrbalan/pagecurl/blob/main/demo/src/main/kotlin/eu/wewox/pagecurl/screens/PagingPageCurlScreen.kt

Also you could try it yourself in freshly released 1.2.0 version:
https://github.com/oleksandrbalan/pagecurl/releases/tag/v1.2.0

**Comment by choristery** [comment]
Hi，I just tried it and now PageCurl already supports Paging pagination. However, due to my slightly complex use case, it doesn't work very well. The scenario is as follows: the data starts from a recorded page number, such as 4, and then Paging will automatically read the third page. But this will cause PageCurl to refresh, and PageCurl seems unable to remember and restore the position by key like Pager does, so when data is inserted ahead, it scrolls to position 0 instead of maintaining the current position. Do you have any good suggestions for this?

**Comment by oleksandrbalan** [comment]
Hmm, I do not think I clearly understand the problem 🤔 

Could you please provide some small reproduction example or maybe a video of such behavior?

**Comment by oleksandrbalan** [comment]
Oh, I see, thx 👀

I will check how this could be fixed 🤔

**Comment by oleksandrbalan** [comment]
@choristery I have added a new `PageCurl` override with "key" lambda in `feature/keys` branch: https://github.com/oleksandrbalan/pagecurl/pull/12

Could you please check if it will work in your case?

**Comment by choristery** [comment]
Hi, I've tried it, and it works fine now. However, at present, there will be a particularly obvious flickering phenomenon when turning pages when there are many contents. Can it be solved?

I uploaded a video：[YouTube](https://youtube.com/shorts/I3KaK-M46bg?feature=share)

**Comment by oleksandrbalan** [comment]
Cool cool, thx for testing 👍 

If I understand correctly it's because you have used a newer compose version. So I have published a new library version 1.3.0 with a `key` lambda support and a fix for newest compose (BOM 2023.03.00). 

https://github.com/oleksandrbalan/pagecurl/releases/tag/v1.3.0

Could you check it if it fixes that flickering? 🙏

**Comment by choristery** [comment]
I've confirmed that it's working fine now, both repositioning and page flip animations. 🙏
